// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kvstore.proto

#include "kvstore.pb.h"
#include "kvstore.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace kvstore {

static const char* KeyValueStore_method_names[] = {
  "/kvstore.KeyValueStore/put",
  "/kvstore.KeyValueStore/get",
  "/kvstore.KeyValueStore/remove",
};

std::unique_ptr< KeyValueStore::Stub> KeyValueStore::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KeyValueStore::Stub> stub(new KeyValueStore::Stub(channel));
  return stub;
}

KeyValueStore::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_put_(KeyValueStore_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_get_(KeyValueStore_method_names[1], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_remove_(KeyValueStore_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KeyValueStore::Stub::put(::grpc::ClientContext* context, const ::kvstore::PutRequest& request, ::kvstore::PutReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kvstore::PutRequest, ::kvstore::PutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_put_, context, request, response);
}

void KeyValueStore::Stub::experimental_async::put(::grpc::ClientContext* context, const ::kvstore::PutRequest* request, ::kvstore::PutReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kvstore::PutRequest, ::kvstore::PutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_put_, context, request, response, std::move(f));
}

void KeyValueStore::Stub::experimental_async::put(::grpc::ClientContext* context, const ::kvstore::PutRequest* request, ::kvstore::PutReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvstore::PutReply>* KeyValueStore::Stub::PrepareAsyncputRaw(::grpc::ClientContext* context, const ::kvstore::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kvstore::PutReply, ::kvstore::PutRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_put_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kvstore::PutReply>* KeyValueStore::Stub::AsyncputRaw(::grpc::ClientContext* context, const ::kvstore::PutRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncputRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::kvstore::GetRequest, ::kvstore::GetReply>* KeyValueStore::Stub::getRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::kvstore::GetRequest, ::kvstore::GetReply>::Create(channel_.get(), rpcmethod_get_, context);
}

void KeyValueStore::Stub::experimental_async::get(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::kvstore::GetRequest,::kvstore::GetReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::kvstore::GetRequest,::kvstore::GetReply>::Create(stub_->channel_.get(), stub_->rpcmethod_get_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::kvstore::GetRequest, ::kvstore::GetReply>* KeyValueStore::Stub::AsyncgetRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::kvstore::GetRequest, ::kvstore::GetReply>::Create(channel_.get(), cq, rpcmethod_get_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::kvstore::GetRequest, ::kvstore::GetReply>* KeyValueStore::Stub::PrepareAsyncgetRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::kvstore::GetRequest, ::kvstore::GetReply>::Create(channel_.get(), cq, rpcmethod_get_, context, false, nullptr);
}

::grpc::Status KeyValueStore::Stub::remove(::grpc::ClientContext* context, const ::kvstore::RemoveRequest& request, ::kvstore::RemoveReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kvstore::RemoveRequest, ::kvstore::RemoveReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_remove_, context, request, response);
}

void KeyValueStore::Stub::experimental_async::remove(::grpc::ClientContext* context, const ::kvstore::RemoveRequest* request, ::kvstore::RemoveReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kvstore::RemoveRequest, ::kvstore::RemoveReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remove_, context, request, response, std::move(f));
}

void KeyValueStore::Stub::experimental_async::remove(::grpc::ClientContext* context, const ::kvstore::RemoveRequest* request, ::kvstore::RemoveReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_remove_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kvstore::RemoveReply>* KeyValueStore::Stub::PrepareAsyncremoveRaw(::grpc::ClientContext* context, const ::kvstore::RemoveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kvstore::RemoveReply, ::kvstore::RemoveRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_remove_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kvstore::RemoveReply>* KeyValueStore::Stub::AsyncremoveRaw(::grpc::ClientContext* context, const ::kvstore::RemoveRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncremoveRaw(context, request, cq);
  result->StartCall();
  return result;
}

KeyValueStore::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KeyValueStore_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KeyValueStore::Service, ::kvstore::PutRequest, ::kvstore::PutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KeyValueStore::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kvstore::PutRequest* req,
             ::kvstore::PutReply* resp) {
               return service->put(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KeyValueStore_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< KeyValueStore::Service, ::kvstore::GetRequest, ::kvstore::GetReply>(
          [](KeyValueStore::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::kvstore::GetReply,
             ::kvstore::GetRequest>* stream) {
               return service->get(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KeyValueStore_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KeyValueStore::Service, ::kvstore::RemoveRequest, ::kvstore::RemoveReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KeyValueStore::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kvstore::RemoveRequest* req,
             ::kvstore::RemoveReply* resp) {
               return service->remove(ctx, req, resp);
             }, this)));
}

KeyValueStore::Service::~Service() {
}

::grpc::Status KeyValueStore::Service::put(::grpc::ServerContext* context, const ::kvstore::PutRequest* request, ::kvstore::PutReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KeyValueStore::Service::get(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::kvstore::GetReply, ::kvstore::GetRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KeyValueStore::Service::remove(::grpc::ServerContext* context, const ::kvstore::RemoveRequest* request, ::kvstore::RemoveReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kvstore

